// apps/react-scrappy/src/app/components/search/index.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import algoliasearch from 'algoliasearch/lite';
import { InstantSearch, SearchBox, Hits } from 'react-instantsearch-dom';

import './search-component.scss';

const appId = process.env.NX_ALGOLIA_APP_ID;
const searchKey = process.env.NX_ALGOLIA_SEARCH_KEY;

const algoliaClient = algoliasearch(appId, searchKey);

const searchClient = {
  ...algoliaClient,
  search(requests) {
    if (
      requests.every(({ params }) => !params.query || params.query.length < 2)
    ) {
      return Promise.resolve({
        results: requests.map(() => ({
          hits: [],
          nbHits: 0,
          nbPages: 0,
          page: 0,
          processingTimeMS: 0,
        })),
      });
    }

    return algoliaClient.search(requests);
  },
};

const resetResults = () => {
  const list = document.getElementsByClassName('ais-SearchBox-reset')[0] as HTMLButtonElement;
  list.click();
};

export function SearchComponent() {
  return (
    <div>
      <InstantSearch searchClient={searchClient} indexName="dictionary">
        <SearchBox
          className="search-box m-2"
          translations={{ placeholder: 'Search word' }}
        />
        <Hits hitComponent={Hit} />
      </InstantSearch>
    </div>
  );
}

const Hit = ({ hit }) => (
  <Link to={`/${hit.language}/word/${hit.word.toLowerCase()}`}>
    <div
      className="list-group-item d-flex justify-content-between align-items-center"
      onClick={(e) => resetResults()}
    >
      <span className="text-white">{hit.word}</span>
      <span className="badge badge-warning badge-pill text-light">
        {hit.language}
      </span>
    </div>
  </Link>
);

// apps/ng-scrappy/src/app/components/search/search.component.ts
import { DOCUMENT } from '@angular/common';
import { Component, Inject } from '@angular/core';
import { Router } from '@angular/router';
import algoliasearch from 'algoliasearch/lite';
import { ITranslationResults } from '@ng-scrappy/models';
import { environment } from '../../../../src/environments/environment';


@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss'],
})
export class SearchComponent {

  config = {
    indexName: 'dictionary',
    searchClient: algoliasearch(
      environment.algoliaConfig.appId,
      environment.algoliaConfig.searchKey,
    ),
  };

  constructor(
    @Inject(DOCUMENT) private _document: HTMLDocument,
    private _router: Router
  ) {}

  goTo(hit: ITranslationResults) {
    this._router.navigate(['/', hit.language, 'words', hit.word]);
    const el = this._document.querySelector('.ais-SearchBox-resetIcon');
    el.parentElement.click();
  }
}

<div class="search-box">
  <ais-instantsearch [config]="config">

    <ais-search-box class="search-box"  placeholder="Search word"></ais-search-box>
    <ais-hits>
      <ng-template let-hits="hits" let-results="results">
        <div *ngIf="results?.query">
          <div *ngFor="let hit of hits" class="content">
            <a (click)="goTo(hit)" class="list-group-item d-flex justify-content-between align-items-center">
              <span class="text-white">{{ hit.word }}</span>
              <span class="badge badge-warning badge-pill text-light">
                {{ hit.language }}
              </span>
          </a>
          </div>
        </div>
      </ng-template>
    </ais-hits>

  </ais-instantsearch>
</div>
