// apps/react-scrappy/src/app/components/translation-detail/index.tsx
import React from 'react';
import { useQuery } from '@apollo/client';

import Skeleton from 'react-loading-skeleton';

import { ITranslation } from '@ng-scrappy/models';
import { Link } from 'react-router-dom';

import Error from './../error';
import { capitalize } from '../../utils/capitalize.util';
import { setAsWord } from '../../utils/space-fixer.util';
import { TRANSLATION_DETAILS_QUERY } from '../../queries/translations.queries';

export function TranslationDetail(props) {
  const { loading, error, data } = useQuery(TRANSLATION_DETAILS_QUERY, {
    variables: { word: props.match.params.word },
  });

  const trl = data ? data.searchWord[0] : (null as ITranslation);
  const lang = props.match.params.language;

  const loaded = trl && lang;

  if (error) return <Error />;

  return (
    <div className="m-2 pb-3 card bg-light">
      <div className="card-header pb-0 d-flex justify-content-between">
        <p className="text-secondary">
          {loaded ? 'Translation' : <Skeleton width={80} />}
        </p>
        <Link to={`/${lang}/words`}>
          {loaded ? (
            <span className="badge badge-warning">{lang}</span>
          ) : (
            <Skeleton width={40} height={12} />
          )}
        </Link>
      </div>
      <div className="card-body">
        <h2 className="card-title">
          {loaded ? setAsWord(trl.word) : <Skeleton width={100} />}
        </h2>
        <p className="card-text">
          {loaded ? (
            trl.meaning ? (
              capitalize(trl.meaning)
            ) : (
              "😬 Meaning wasn't provided"
            )
          ) : (
            <Skeleton count={1} width={250} className="d-block mb-2" />
          )}
        </p>
      </div>

      <hr />

      <div className="card-body mb-0">
        <p className="text-muted">
          {loaded ? 'Example' : <Skeleton width={100} />}
        </p>
        <p>
          {loaded ? (
            trl.example ? (
              capitalize(trl.example)
            ) : (
              '😞 No example available.'
            )
          ) : (
            <Skeleton />
          )}
        </p>
        <p className="text-muted">
          {loaded ? 'Translated to...' : <Skeleton width={150} />}
        </p>
        <p>
          {loaded ? (
            trl.translation ? (
              capitalize(trl.translation)
            ) : (
              "😞 The translation wasn't provided."
            )
          ) : (
            <Skeleton />
          )}
        </p>
      </div>

      <hr />

      <div className="card m-3 bg-light border-secondary">
        <p className="text-secondary p-2 mb-0">
          {loaded ? 'Related Words' : <Skeleton width={150} />}
        </p>

        <div className="list-group list-group-flush m-0 p-0">
          {loaded ? (
            trl.relatedWords.map((word, i) => (
              <Link to={`/${lang}/word/${word.toLowerCase()}`} key={i}>
                <u key={word} className="list-group-item pl-2 text-dark">
                  {capitalize(word)}
                </u>
              </Link>
            ))
          ) : (
            <Skeleton
              count={4}
              height={14}
              width={45}
              className={'ml-2 mb-3 mt-3 d-block'}
            />
          )}
        </div>
      </div>
    </div>
  );
}

// apps/ng-scrappy/src/app/components/translation-detail/translation-detail.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'translation-detail',
  templateUrl: './translation-detail.component.html',
  styleUrls: ['./translation-detail.component.scss']
})
export class TranslationDetailComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="wrapper m-auto">
  <div *ngIf="trlData$ | async as trl" class="m-2 pb-3 card bg-light">
    <div class="card-header pb-0 d-flex justify-content-between">
      <p class="text-secondary">
        Translation
      </p>
      <a [routerLink]="['/', trl.language, 'words']">
        <span class="badge badge-warning">{{ trl.language | titlecase }}</span>
      </a>
    </div>
    <div class="card-body">
      <h2 class="card-title">
        {{ trl.word | titlecase }}
      </h2>
      <p class="card-text">
        {{ trl.meaning ? (trl.meaning | capitalize) : "😬 Meaning wasn't provided" }}
      </p>
    </div>

    <hr />

    <div class="card-body mb-0">
      <p class="text-muted">
        Example
      </p>
      <p>
        {{ trl.example ? (trl.example | capitalize) : "😞 No example available." }}
      </p>

      <p class="text-muted">
        Translated to...
      </p>

      <p>
        {{ trl.translation ? (trl.translation | capitalize) : "😞 The translation wasn't provided." }}
      </p>
    </div>

    <hr />

    <div class="card m-3 bg-light border-secondary">
      <p class="text-secondary p-2 mb-0">
        Related Words
      </p>

      <div *ngFor="let related of trl.relatedWords" class="list-group list-group-flush m-0 p-0">
        <a [routerLink]="['/', trl.language, 'words', related]">
          <u class="list-group-item pl-2 text-dark">
            {{ related | titlecase }}
          </u>
        </a>
      </div>
    </div>
  </div>

</div>
