// apps/ng-scrappy/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { combineLatest, Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { ILanguage, LanguageStatus } from '@ng-scrappy/models';

import { ActiveLangService } from '../../services/active-lang.service';
import { DbService } from '../../services/db.service';

@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  lang$: Observable<ILanguage>;
  supportedLangs$: Observable<ILanguage[]>

  constructor(
    private _dict$: DbService,
    private _lang$: ActiveLangService) {}

  ngOnInit(): void {

    const activeLang$ = this._lang$.getActiveLang();
    this.supportedLangs$ = this._dict$.getLanguageData(LanguageStatus.Supported);

    this.lang$ = combineLatest([activeLang$, this.supportedLangs$])
                  .pipe(map(([active, langs]) => langs.find(l => l.language === active)));

  }
}

<div *ngIf="lang$ | async as lang">

  <div class="card bg-light border-warning m-2">
    <span class="card-header text-warning">
      Language
    </span>

    <div class="card-body">
      <h1 class="card-title">
        {{lang.language}}
      </h1>
      <p class="card-text">
        {{lang.description}}
      </p>
    </div>
    <div class="card-footer">
      <p class="card-text">

        <button [routerLink]="['/', lang.language, 'words']" class="btn btn-outline-warning">
          Open dictionary
        </button>
      </p>
    </div>
  </div>

  <hr />

  <div class="card bg-light border-light m-2 p-3">
    <h5 class="text-center text-dark text-capitalize">
      Popular {{ lang.language }} Searches
    </h5>

    <div class="scrolling-wrapper d-flex flex-row mt-2">
      <popular *ngFor="let word of lang.popular" [language]="lang.language" [word]="word"></popular>
    </div>
  </div>

  <hr />

  <div class="jumbotron bg-light border-secondary pt-4 pb-5">
    <h5 class="text-center text-dark">
      More Languages
    </h5>

    <div class="scrolling-wrapper d-flex pb-1 pt-1">
          <app-language *ngFor="let lang of supportedLangs$ | async" [lang]="lang"></app-language>
    </div>
  </div>

  <div class="jumbotron bg-light border-secondary pt-4 pb-5">
    <app-vote-card></app-vote-card>
  </div>
</div>

// apps/react-scrappy/src/app/components/home.tsx
import React, { Fragment } from 'react';
import { useQuery, gql } from '@apollo/client';
import { ILanguage } from '@ng-scrappy/models';
import { capitalize } from '../utils/capitalize.util';
import { Link } from 'react-router-dom';
import LanguageCard from './language-card';
import PopularElement from './popular-element';

const WORDS_LIST_QUERY = gql`
  query GetLanguageWords($language: String!) {
    translations(language: $language) {
      word
      language
      meaning
    }
  }
`;

const LANGUAGES_QUERY = gql`
  query GetLanguages {
    languages {
      language
      description
      popular
    }
  }
`;

export default function Home(props) {
  const { loading, error, data } = useQuery(WORDS_LIST_QUERY, {
    variables: { language: props.match.params.language },
  });

  const langsData = useQuery(LANGUAGES_QUERY);
  const supportedLangs: ILanguage[] = langsData?.data?.languages ?? [];

  const lang = props.match.params.language;
  const activeLang = supportedLangs.find(l => l.language === lang);
  const otherLangs = supportedLangs.filter(l => l.language !== lang);

  if (loading || !activeLang) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;



  return (
    <div>
      <div className="card  bg-light border-warning m-2">
        <span className="card-header text-warning">Language</span>
        <div className="card-body">
          <h1 className="card-title">{capitalize(lang)}</h1>
          <p className="card-text">
            {capitalize(activeLang.description)}
          </p>
        </div>
        <div className="card-footer">
          <Link to={`/${lang}/words`}>
            <button className="btn btn-outline-warning">Open dictionary</button>
          </Link>
        </div>
      </div>

      <hr/>

      <div className="card bg-light border-light m-2 p-3">
        <h5 className="text-center text-dark text-capitalize">Popular {lang} Searches</h5>

        <div className="scrolling-wrapper d-flex mt-2">
          {activeLang.popular.map((word) => (
            <PopularElement key={lang.word} language={lang} word={word} />
          ))}
        </div>
      </div>

      <hr />

      <div className="jumbotron bg-light border-secondary m-2">
        <h5 className="text-center text-dark">More Languages</h5>

        <div className="scrolling-wrapper d-flex mt-2 pb-2 pt-2">
          {otherLangs.map((lang: ILanguage) => (
            <LanguageCard key={lang.language} language={lang} />
          ))}
        </div>
      </div>
    </div>
  );
}
