// apps/ng-scrappy/src/app/components/translation-detail/translation-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { ITranslationResults } from '@ng-scrappy/models';
import { DbService } from '../../services/db.service';

@Component({
  selector: 'translation-detail',
  templateUrl: './translation-detail.component.html',
  styleUrls: ['./translation-detail.component.scss'],
})
export class TranslationDetailComponent implements OnInit {
  trlData$: Observable<ITranslationResults>;

  constructor(private _route: ActivatedRoute, private _dict$: DbService) {}

  ngOnInit(): void {
    const queryData$ = this._route.params.pipe(
      map((params) => {
        const { language, word } = params;
        return { language, word };
      })
    );

    this.trlData$ = queryData$.pipe(
      switchMap((query) => {
        return this._dict$.getWordTrl(query.language, query.word);
      })
    );
  }
}

<div class="wrapper m-auto">
  <div *ngIf="trlData$ | async as trl" class="m-2 pb-3 card bg-light">
    <div class="card-header pb-0 d-flex justify-content-between">
      <p class="text-secondary">
        Translation
      </p>
      <a [routerLink]="['/', trl.language, 'words']">
        <span class="badge badge-warning">{{ trl.language | titlecase }}</span>
      </a>
    </div>
    <div class="card-body">
      <h2 class="card-title">
        {{ trl.word | titlecase }}
      </h2>
      <p class="card-text">
        {{ trl.meaning ? (trl.meaning | capitalize) : "😬 Meaning wasn't provided" }}
      </p>
    </div>

    <hr />

    <div class="card-body mb-0">
      <p class="text-muted">
        Example
      </p>
      <p>
        {{ trl.example ? (trl.example | capitalize) : "😞 No example available." }}
      </p>

      <p class="text-muted">
        Translated to...
      </p>

      <p>
        {{ trl.translation ? (trl.translation | capitalize) : "😞 The translation wasn't provided." }}
      </p>
    </div>

    <hr />

    <div class="card m-3 bg-light border-secondary">
      <p class="text-secondary p-2 mb-0">
        Related Words
      </p>

      <div *ngFor="let related of trl.relatedWords" class="list-group list-group-flush m-0 p-0">
        <a [routerLink]="['/', trl.language, 'words', related]">
          <u class="list-group-item pl-2 text-dark">
            {{ related | titlecase }}
          </u>
        </a>
      </div>
    </div>
  </div>

</div>

// apps/react-scrappy/src/app/components/translation-detail.tsx
import React, { Fragment } from 'react';
import { useQuery, gql } from '@apollo/client';
import { ITranslation } from '@ng-scrappy/models';
import { Link } from 'react-router-dom';

import { capitalize } from '../utils/capitalize.util';


const WORD_QUERY = gql`
  query GetWordTranslation($word: String!) {
    translations(word: $word) {
      word
      language
      meaning
      example
      translation
      relatedWords
    }
  }
`;

export default function TranslationDetail(props) {
  const { loading, error, data } = useQuery(WORD_QUERY, {
    variables: { word: props.match.params.word },
  });

  const trl = data ? data.translations[0] : null as ITranslation;
  const lang = props.match.params.language;

  if (loading || (!trl)) return <p>Loading word...</p>;
  if (error) return <p>Error loading word :(</p>;


  return(
    <div className="m-2 pb-3 card bg-light">
      <div className="card-header pb-0 d-flex justify-content-between">
        <p className="text-secondary">Translation</p>
        <Link to={`/${lang}/words`}>
          <span className="badge badge-warning">{lang}</span>
        </Link>
      </div>
      <div className="card-body">
        <h2 className="card-title">{capitalize(trl.word)}</h2>
        <p className="card-text">{trl.meaning ? capitalize(trl.meaning) : `😬 Meaning wasn't provided`}</p>
      </div>

      <hr/>

      <div className="card-body mb-0">
        <p className="text-muted">Example</p>
        <p>{trl.example ? capitalize(trl.example) : `😞 No example available.`}</p>
        <p className="text-muted">Translated to...</p>
        <p>{trl.translation ? capitalize(trl.translation) : `😒 No translation provided!`}</p>
      </div>

      <hr/>

      <div className="card m-3 bg-light border-secondary">
        <p className="text-secondary p-2 mb-0">Related Words</p>

        <div className="list-group list-group-flush m-0 p-0">
          {trl.relatedWords.map((word, i) =>
            <Link to={`/${lang}/word/${word.toLowerCase()}`}>
              <u key={word} className="list-group-item pl-2 text-dark">{capitalize(word)}</u>
            </Link>
          )}
        </div>
      </div>
    </div>
  )

}
